### ISSUE TITLE
undefined is not an object (evaluating 'serializer.serialize')

### ISSUE THREAD

**Issue by belliAndrea** [Ecostack/localForage-cordova-sqlite-plugin#1]
I just installed the plugin but seems like i cannot set any items in it.

I'm using it with Ionic and obviously cordova sqlite plugin.
In angular-forage i configure the driver like this:
$localForageProvider.config({
        driver      : 'cordova-sqlite-plugin', 
        name        : 'mg',
        storeName   : 'keyvaluepairs'
    });

then when i setItem() i got this error:
 "undefined is not an object (evaluating 'serializer.serialize')"

**Comment by Ecostack** [comment]
Hey Andrea,

is there any other console output and could you please send me the complete error message?

**Comment by belliAndrea** [comment]
mh not really, the real problem is that i don't have this one

  resolve(globalObject.localforageSerializer);

where can i get localforageSerializer?

**Comment by Ecostack** [comment]
Have you looked at https://github.com/mozilla/localForage/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+localforageSerializer ?

And have you tried the normal websql driver from localForage? There should be the same issue.
