### ISSUE TITLE
 No available storage method found

### ISSUE THREAD

**Issue by belliAndrea** [Ecostack/localForage-cordova-sqlite-plugin#2]
Sometimes when my app starts seems like i cannot manage to set the driver.
and i get <b> No available storage method found. </b>

Here the localForage lib ref:

```
    this._driverSet = new Promise(function(resolve, reject) {
        var driverName = self._getFirstSupportedDriver(drivers);
        var error = new Error('No available storage method found.');

        if (!driverName) {
            self._driverSet = Promise.reject(error);
            reject(error);
            return;
        }
```

**Comment by belliAndrea** [comment]
the problem is in the checkSupport method, i don't know but maybe the _support value is populated too late by the deviceready callback or maybe the promise callback function sometimes is called after the deviceready is fired.

```
 function checkSupport() {
    return new Promise(function(resolve, reject) {
        document.addEventListener("deviceready", function() {
            resolve(globalObject.sqlitePlugin != null);
        }, false);
    });
}
```

if i put a boolean to _support, all seems to work fine.

```
var cordovaSqliteplugin = {
    _driver: 'cordova-sqlite-plugin',
    _initStorage: _initStorage,
   _support: true
  ....
 }
```

**Comment by Ecostack** [comment]
An event listener for the deviceready event should always be triggered, even if the event has already been fired. See http://docs.phonegap.com/en/edge/cordova_events_events.md.html#deviceready

I have read you are using Ionic, are there any problems with deviceready? Have you looked at this?
https://github.com/driftyco/ionic-cli/issues/259

**Comment by Ecostack** [comment]
Also this applies to Steroids, which we are using. And here it also happens sometimes..
https://github.com/AppGyver/steroids/issues/772

**Comment by Ecostack** [comment]
There is now a variant of the script without the support check.
